### ISSUE TITLE
How to write acknowledgement (commitments) in the IBC module?

### ISSUE THREAD

**Issue by livelybug** [octopus-network/hermes#89]
Discuss the solution of the [issue](https://github.com/informalsystems/ibc-rs/issues/1525) according to Adi's reply.

Testing env:
Repo | Branch | Commit
-- | -- | --
substrate | dv-ibc-dev | fbff4a4b135e59d4e87ff6f5590d6c4758145d2d
substrate-ibc | cs-dev | 6628dfe80cfdd5536086a391cea5ecb944369091
ibc-rs | cs-dev | 89d815eaea47e7bfb8e8715ea67072b48234c1b2

**Comment by livelybug** [comment]
updated testing env

Repo | Branch | Commit
-- | -- | --
substrate | dv-ibc-dev | fbff4a4b135e59d4e87ff6f5590d6c4758145d2d
substrate-ibc | dv-ibc-dev | latest
ibc-rs | dv-octopus-relayer | latest

**Comment by boern** [comment]
The best time is after receive packet event  and write the ack packet to substrate app chain.
