### ISSUE TITLE
COUNTER_SYSTEM_EVENT & Fail to establish channel

### ISSUE THREAD

**Issue by livelybug** [octopus-network/hermes#96]
The variable `COUNTER_SYSTEM_EVENT` is increased from 5 to 10 in [the commit](https://github.com/octopus-network/ibc-rs/commit/5080dd92a3360e165bacfba0f55bccecf0cee60b#diff-d7b19e3de5e5d207f340275b5016e425b2adefe336c6625fcb2e785681942defL101).

Before the increase, the command ` cargo run -- -c hermes.toml create channel ibc-0 earth --port-a transfer --port-b transfer -o unordered` hit an assertion error:
```
 8: ibc_relayer::foreign_client::ForeignClient<DstChain,SrcChain>::build_create_client_and_send::ha8069362f7e4c2b3
    at /ibc/ibc-rs/relayer/src/foreign_client.rs:513
     511 │ 
     512 │ 
     513 >         assert!(!res.is_empty());
     514 │         Ok(res[0].clone())
```

Need further investment to understand `COUNTER_SYSTEM_EVENT` better.

**Comment by boern** [comment]
Change the COUNTER_SYSTEM_EVENT  to 8 for less time!
